### ISSUE TITLE
The Inquiry about dataset download 

### ISSUE THREAD

**Issue by gersys** [HuiGuanLab/ms-sl#3]
Hi I'm Cheol-Ho Cho, a graduate student in Korea

Thank you for your great work and I'm really interested in it.

I have downloaded the dataset you prepared by 'Aliyun'

But, there are only text features except for tvr dataset 
(activitynet and charades only include text features)

Can you upload visual features of activitynet and charades to Aliyun link?

because I can't download it by Baidu pan, because I'm a foreigner.

I would be very thankful if you help me

Best regard

**Comment by cxkxk** [comment]
Thank you for your issue, we have updated the missing features and you can get the full dataset now.

**Comment by gersys** [comment]
Thank you for your reply

I checked the download link, but there is an error occurred

` wget http://8.210.46.84:8787/prvr/data/activitynet.tar
--2023-06-19 12:20:14--  http://8.210.46.84:8787/prvr/data/activitynet.tar
Connecting to 8.210.46.84:8787... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-06-19 12:20:14 ERROR 404: Not Found.`

The error is also occurred in charades dataset 

Could you check it one more time?

**Comment by gersys** [comment]
I can download them now 

thank you
