### ISSUE TITLE
Code for DL-DKD

### ISSUE THREAD

**Issue by Lonicer** [HuiGuanLab/ms-sl#7]
After reading your article (Dual Learning with Dynamic Knowledge Distillation for Partially Relevant Video Retrieval), I am very interested and want to follow up on related work. When will you upload the code?

**Comment by chuanshen-chen** [comment]
Me too, Looking forward to

**Comment by danieljf24** [comment]
Our source code has been released at https://github.com/HuiGuanLab/DL-DKD
