### ISSUE TITLE
Code for Dual Learning with Dynamic Knowledge Distillation for Partially Relevant Video Retrieval

### ISSUE THREAD

**Issue by chuanshen-chen** [HuiGuanLab/ms-sl#8]
Github projects mentioned in the paper （https://github.com/HuiGuanLab/DL-DKD）does not exist，After reading your article (Dual Learning with Dynamic Knowledge Distillation for Partially Relevant Video Retrieval), I am very interested and want to follow up on related work. When will you upload the code?

**Comment by danieljf24** [comment]
Our source code has been released at https://github.com/HuiGuanLab/DL-DKD
